In [1]:
import requests
res = requests.get('http://mops.twse.com.tw/server-java/t164sb01?step=1&CO_ID=1101&SYEAR=2017&SSEASON=3&REPORT_ID=C')

In [7]:
res.encoding = 'big5'
from io import StringIO
import pandas as pd
dfs = pd.read_html(StringIO(res.text))

In [12]:
dfs[3].head()

                0                        1                        2
0            會計項目  2017年01月01日至2017年09月30日  2016年01月01日至2016年09月30日
1           現金流量表                      NaN                      NaN
2   營業活動之現金流量－間接法                      NaN                      NaN
3  繼續營業單位稅前淨利（淨損）                  9226556                  7771113
4      本期稅前淨利（淨損）                  9226556                  7771113

In [16]:
import os
import time
sid = ['1101','2330']

for s in sid:
    res = requests.get('http://mops.twse.com.tw/server-java/t164sb01?step=1&CO_ID='+s+'&SYEAR=2017&SSEASON=3&REPORT_ID=C')
    res.encoding = 'big5'
    path = os.path.join('course9',s+'.html')
    f=open(path,'w')
    f.write(res.text)
    f.close()
    
    print(s)
    
    time.sleep(10)

1101
2330

In [17]:
dfs = []
for s in sid:
    path = os.path.join('course9',s+'.html')
    dfs.append(pd.read_html(path))

In [18]:
dfs[0]

[       0   1   2    3                                4    5            6  \
 0  公司代號： NaN NaN  年度：  102 103 104 105 106 107 108 109  季別：  第 1 2 3 4 季

        7               8   9
 0  財報類別：  合併財報 個別財報 個體財報 NaN  ,
                              0            1            2            3
 0                         會計項目  2017年09月30日  2016年12月31日  2016年09月30日
 1                        資產負債表          NaN          NaN          NaN
 2                           資產          NaN          NaN          NaN
 3                         流動資產          NaN          NaN          NaN
 4                      現金及約當現金          NaN          NaN          NaN
 5                    現金及約當現金合計     26608300     28179758     27229371
 6          透過損益按公允價值衡量之金融資產－流動          NaN          NaN          NaN
 7        透過損益按公允價值衡量之金融資產－流動合計       147571       148488       162966
 8                  備供出售金融資產－流動          NaN          NaN          NaN
 9                備供出售金融資產－流動淨額     20061583     15536693     15375305
 10                      應收票據淨額          NaN          NaN          NaN
 11                      應收票據淨額     15800456     12600411     10128788
 12                      應收帳款淨額          NaN          NaN          NaN
 13                      應收帳款淨額      6800265      6782292      6042259
 14                  應收帳款－關係人淨額          NaN          NaN          NaN
 15                  應收帳款－關係人淨額       205600       546984       769611
 16                       其他應收款          NaN          NaN          NaN
 17                     其他應收款淨額       410446       770838       604825
 18                   其他應收款－關係人          NaN          NaN          NaN
 19                 其他應收款－關係人淨額       214394       181997       567371
 20                          存貨          NaN          NaN          NaN
 21                        存貨合計      9493855      8893965      8221800
 22                        預付款項          NaN          NaN          NaN
 23                      預付款項合計      3967788      2955246      3570376
 24                      其他流動資產          NaN          NaN          NaN
 25                   其他金融資產－流動       950591       812127       955826
 26                   其他流動資產－其他       659353       475213       549677
 27                    其他流動資產合計      1609944      1287340      1505503
 28                      流動資產合計     85320202     77884012     74178175
 29                       非流動資產          NaN          NaN          NaN
 ..                         ...          ...          ...          ...
 73                    其他流動負債合計     16767434     11591214     18373500
 74                      流動負債合計     65268003     55104919     61983521
 75                       非流動負債          NaN          NaN          NaN
 76                        長期借款          NaN          NaN          NaN
 77                      長期借款合計     40246010     53342059     46359096
 78                     遞延所得稅負債          NaN          NaN          NaN
 79                   遞延所得稅負債合計     10282372     10213967     10271611
 80                     其他非流動負債          NaN          NaN          NaN
 81                 淨確定福利負債-非流動       160052       184115       191831
 82                  其他非流動負債－其他       534890       746965       813983
 83                   其他非流動負債合計       694942       931080      1005814
 84                     非流動負債合計     51223324     64487106     57636521
 85                        負債總計    116491327    119592025    119620042
 86                          權益          NaN          NaN          NaN
 87                 歸屬於母公司業主之權益          NaN          NaN          NaN
 88                          股本          NaN          NaN          NaN
 89                       普通股股本     36921759     36921759     36921759
 90                        股本合計     36921759     36921759     36921759
 91                        資本公積          NaN          NaN          NaN
 92                      資本公積合計     13535897     13534162     13534162
 93                        保留盈餘          NaN          NaN          NaN
 94                      保留盈餘合計     46932681     47337524     45208495
 95                        其他權益          NaN          NaN          NaN
 96                      其他權益合計     14831885      8974606      9511612
 97               歸屬於母公司業主之權益合計    112222222    106768051    105176028
 98                       非控制權益     40744347     40628620     40281876
 99                        權益總計    152966569    147396671    145457904
 100                    負債及權益總計    269457896    266988696    265077946
 101          預收股款（權益項下）之約當發行股數            0            0            0
 102  母公司暨子公司所持有之母公司庫藏股股數（單位：股）            0            0            0

 [103 rows x 4 columns],
                                        0         1         2  \
 0                                   會計項目  2017年第3季  2016年第3季
 1                                  綜合損益表       NaN       NaN
 2                                   營業收入       NaN       NaN
 3                                 營業收入合計  23058257  22350039
 4                                   營業成本       NaN       NaN
 5                                 營業成本合計  18801014  17390791
 6                               營業毛利（毛損）   4257243   4959248
 7                             營業毛利（毛損）淨額   4257243   4959248
 8                                   營業費用       NaN       NaN
 9                                   推銷費用       NaN       NaN
 10                                推銷費用合計    188481    173775
 11                                  管理費用       NaN       NaN
 12                                管理費用合計    815035    999161
 13                                研究發展費用       NaN       NaN
 14                              研究發展費用合計      7878      5777
 15                                營業費用合計   1011394   1178713
 16                              營業利益（損失）   3245849   3780535
 17                              營業外收入及支出       NaN       NaN
 18                                  其他收入       NaN       NaN
 19                                  利息收入       NaN       NaN
 20                                利息收入合計     58830     75730
 21                                  股利收入    501087    554354
 22                               其他收入－其他     57942     43324
 23                                其他收入合計    617859    673408
 24                               其他利益及損失       NaN       NaN
 25                         處分不動產、廠房及設備利益       734      2338
 26                                  什項支出    242161    149939
 27                                外幣兌換損失      6833    113176
 28                透過損益按公允價值衡量之金融資產（負債）損失     -3874    -15465
 29                             其他利益及損失淨額   -244386   -245312
 30                                  財務成本       NaN       NaN
 31                                財務成本淨額    477503    469390
 32                    採用權益法之關聯企業及合資損益之份額       NaN       NaN
 33                採用權益法認列之關聯企業及合資損益之份額淨額    330407    285827
 34                            營業外收入及支出合計    226377    244533
 35                        繼續營業單位稅前淨利（淨損）   3472226   4025068
 36                             所得稅費用（利益）       NaN       NaN
 37                           所得稅費用（利益）合計    785176    741847
 38                        繼續營業單位本期淨利（淨損）   2687050   3283221
 39                              本期淨利（淨損）   2687050   3283221
 40                            其他綜合損益(淨額)       NaN       NaN
 41                         後續可能重分類至損益之項目       NaN       NaN
 42                     國外營運機構財務報表換算之兌換差額   2125865  -2747322
 43                       備供出售金融資產未實現評價損益   2709169   1131470
 44             現金流量避險中屬有效避險部分之避險工具利益(損失)         0        95
 45  採用權益法認列關聯企業及合資之其他綜合損益之份額-可能重分類至損益之項目       NaN       NaN
 46  採用權益法認列關聯企業及合資之其他綜合損益之份額-可能重分類至損益之項目     91716   -252658
 47                       後續可能重分類至損益之項目總額   4926750  -1868415
 48                            其他綜合損益（淨額）   4926750  -1868415
 49                              本期綜合損益總額   7613800   1414806
 50                             淨利（損）歸屬於：       NaN       NaN
 51                              母公司業主（淨利       NaN       NaN

                           3                        4
 0   2017年01月01日至2017年09月30日  2016年01月01日至2016年09月30日
 1                       NaN                      NaN
 2                       NaN                      NaN
 3                  68952108                 63016298
 4                       NaN                      NaN
 5                  56428105                 51410157
 6                  12524003                 11606141
 7                  12524003                 11606141
 8                       NaN                      NaN
 9                       NaN                      NaN
 10                   572965                   534636
 11                      NaN                      NaN
 12                  2678402                  3020442
 13                      NaN                      NaN
 14                    24465                    15976
 15                  3275832                  3571054
 16                  9248171                  8035087
 17                      NaN                      NaN
 18                      NaN                      NaN
 19                      NaN                      NaN
 20                   171328                   223690
 21                   796998                   801130
 22                   250955                   318759
 23                  1219281                  1343579
 24                      NaN                      NaN
 25                     4413                    33205
 26                   499646                   241342
 27                   217619                   633619
 28                   103849                   -15715
 29                  -816701                  -826041
 30                      NaN                      NaN
 31                  1420845                  1440271
 32                      NaN                      NaN
 33                   996650                   658759
 34                   -21615                  -263974
 35                  9226556                  7771113
 36                      NaN                      NaN
 37                  2305015                  1684433
 38                  6921541                  6086680
 39                  6921541                  6086680
 40                      NaN                      NaN
 41                      NaN                      NaN
 42                   517086                 -5636065
 43                  5849656                   -44940
 44                   -13167                    -9145
 45                      NaN                      NaN
 46                  -156024                  -479839
 47                  6197551                 -6169989
 48                  6197551                 -6169989
 49                 13119092                   -83309
 50                      NaN                      NaN
 51                      NaN                      NaN  ]